mlflow_experiment_name: test_experiment_1
model_name: test_model_1
num_epochs: 10
lr: 0.0001
train_split: 0.8
test_split: 0.05
batch_size: 1
num_workers: 16
loss: 
  name: CrossEntropyLoss
model:
  name: PretrainedTransformerClf
  args:
    num_classes: 17
dataset:
  name: LocalMINDDataset
  args:
    text_col: title
    target_col: category